spring.application.name=todos-service

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Spring AI (OpenAI)
# spring.ai.openai.api-key=${OPENAI_API_KEY:}
# spring.ai.openai.chat.options.model=${OPENAI_MODEL:gpt-4o-mini}

# OpenAPI / Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html